### ISSUE TITLE
"Trapdoor functions" in README

### ISSUE THREAD

**Issue by AGWA** [tollmanz/diffie-hellman-key-exchange-demo#1]
The README mentions trapdoor functions, but Diffie-Hellman doesn't use trapdoor functions.  Unlike RSA, where decryption is the inverse of encryption, there are no inversions involved in Diffie-Hellman, and hence no need for a trapdoor.  Instead, the modular exponentiation that underpins Diffie-Hellman's security is simply a "one-way function."

**Comment by tollmanz** [comment]
Thanks for the clarification. I fixed this. Please let me know if you see any other such issues.
